const errorHandler = (cb: any) => Promise.resolve(cb).catch((err) => err);
